### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by emalema** [emalema/protospace-39396#1]
#URL
https://protospace-39396.onrender.com

**Comment by motomuun** [comment]
@emalema さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**コメント機能**

- [ ] **フォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**
エラーページに遷移します。フォームを空のまま投稿しても、エラーページに遷移せず、元のページに留まるように修正をお願いします。

**ユーザー詳細機能**

- [ ] **ログイン・ログアウトの状態に関わらず、各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移すること**
ログアウト状態ではユーザー詳細ページに遷移できません。遷移できるように修正をお願いします。


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by shodai-ito** [comment]
@emalema さん、再度ご提出ありがとうございます‼︎
上記指摘内容の一部修正が確認できました！
改めて動作の確認をしたところ、引き続き修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
### **`コメント機能`**
- [ ] **フォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**
空のコメントを投稿すると、ページに留まらずエラーになってしまいます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by motomuun** [comment]
@emalema さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
